@startuml
'https://plantuml.com/class-diagram
'关联关系

class Person {
    idCard: IDCard
}
class IDCard {
    person: Person
}

'单向关系
'Person "1" --> "1" IDCard: 单向关联

'双向关系
Person "1" -- "1" IDCard : 双向关联

@enduml